steps:   
#Building image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
          'build',
          '-t', 'gcr.io/$PROJECT_ID/appengine/ts-ws-template:latest', 
          '-f', 'deploy/Dockerfile',
          '.' 
        ]

# Push Images       
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/appengine/ts-ws-template:latest'] 
  

# Deploy to GAE
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'app'
  - 'deploy'
  - 'deploy/env/${_ENV}/app.yaml'
  - '--image-url'
  - 'gcr.io/$PROJECT_ID/appengine/ts-ws-template:latest'
  - '${_PROMOTE}'