service: typescript-ws-template
runtime: nodejs8
instance_class: F4
automatic_scaling:
  min_instances: 1
env_variables:
  PG_USER: pguser
  PG_DB: pgdb
  INSTANCE_CONNECTION_NAME: /cloudsql/<project>:<region>:<pgdb>
  REDIS_HOST: redishost.com
  REDIS_PORT: 1234
  REDIS_DB_INDEX: 0

  # Note that the secrets below are populated in the cloudbuild.yaml script from substitution variables
  PG_PASSWORD: password
  REDIS_PASSWORD: password
